[package]
name = "cffi-lev3"
version = "0.1.0"
authors = ["Sean Jensen-Grey <seanj@xyke.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cffi_lev3"
crate-type = ["cdylib"]


[dependencies]
strsim = "0.10.0"
